#!/usr/bin/env node
/* Writes docs/THEMES.md from the token metadata, so the reference cannot drift
   from the code. Run it after changing DEFAULTS. `node tools/make-docs.js` */
'use strict';
var fs = require('fs');
var vm = require('vm');
var path = require('path');
var ROOT = path.join(__dirname, '..');
var r = function (p) { return fs.readFileSync(path.join(ROOT, p), 'utf8'); };

var ctx = vm.createContext({
  btoa: function (s) { return Buffer.from(s, 'binary').toString('base64'); },
  atob: function (s) { return Buffer.from(s, 'base64').toString('binary'); }
});
vm.runInContext(r('src/theme.js') + '\n' + r('src/themes.js'), ctx);

/* the trailing comment on a DEFAULTS line is the token's documentation */
var notes = {};
r('src/theme.js').split('\n').forEach(function (line) {
  var m = /^\s{2}([a-zA-Z0-9]+):\s*.*?\/\*\s*(.*?)\s*\*\//.exec(line);
  if (m) notes[m[1]] = m[2];
});

/* a bare pipe would end the table cell it sits in */
function cell(s) { return String(s).replace(/\|/g, '\\|'); }

function describe(key) {
  if (notes[key]) return cell(notes[key]);
  if (ctx.ENUM_VALUES[key]) return cell(ctx.ENUM_VALUES[key].join(' | '));
  if (ctx.COLOR_KEYS[key]) return 'hex colour';
  if (typeof ctx.DEFAULTS[key] === 'boolean') return cell('true | false');
  if (ctx.RANGES[key]) return ctx.RANGES[key][0] + ' to ' + ctx.RANGES[key][1];
  return 'text';
}

var out = [];
out.push('# Theme tokens');
out.push('');
out.push('A theme is a JSON object. Every field is optional — anything you leave out');
out.push('falls back to the default below, so the smallest useful theme is a couple of');
out.push('colours. There is no per-theme CSS anywhere in the project: these tokens are');
out.push('the entire vocabulary, and the built-in themes use nothing you cannot.');
out.push('');
out.push('You do not have to write these by hand. Open `theme-builder.html` in a normal');
out.push('browser, design what you want, and copy the code it gives you.');
out.push('');
out.push('**This file is generated by `node tools/make-docs.js`. Edit `src/theme.js` instead.**');
out.push('');
out.push('## Reference');
out.push('');

ctx.FIELD_GROUPS.forEach(function (g) {
  out.push('### ' + g.title);
  out.push('');
  out.push('| Token | Default | Accepts | In Basics |');
  out.push('|---|---|---|---|');
  g.fields.forEach(function (f) {
    var k = f[0];
    var d = ctx.DEFAULTS[k];
    var shown = d === '' ? '_derived_' : '`' + JSON.stringify(d) + '`';
    out.push('| `' + k + '` | ' + shown + ' | ' + describe(k) + ' | '
      + (ctx.BASIC_FIELDS[k] ? 'yes' : '' ) + ' |');
  });
  out.push('');
});

out.push('## Derived colours');
out.push('');
out.push('Tokens marked _derived_ work themselves out from another colour when left');
out.push('empty — `paper2` and `curl` from `paper`, `titleColor` and `checkColor` from');
out.push('`ink`. Set one explicitly and it stops deriving. In the builder these are the');
out.push('fields with an **Auto** tick next to them.');
out.push('');
out.push('Deriving happens in JavaScript rather than in CSS (`color-mix()` and relative');
out.push('colour syntax need a newer Chromium than some shipping OBS builds carry), so a');
out.push('theme renders the same on old and new OBS alike.');
out.push('');
out.push('## Sharing a theme');
out.push('');
out.push('The builder produces a code starting `sn1:` — base64 of the JSON, carrying');
out.push('only the fields that differ from the defaults. Paste it into the note\'s');
out.push('**Theme** panel in the OBS dock. Raw JSON works there too, if you would rather');
out.push('hand-edit.');
out.push('');
out.push('Codes are self-contained, so a theme is one paste to share and does not depend');
out.push('on the version of the note that made it: unknown fields are ignored and missing');
out.push('ones take their defaults.');
out.push('');
out.push('## Built-in themes');
out.push('');
out.push('| Theme | `id` | Tokens it sets |');
out.push('|---|---|---|');
ctx.BUILTINS.forEach(function (b) {
  var n = Object.keys(b).filter(function (k) {
    return k !== 'id' && k !== 'label' && k !== 'swatch';
  }).length;
  out.push('| ' + b.label + ' | `' + b.id + '` | ' + n + ' |');
});
out.push('');
out.push('**Asylum Life** is the one that shaped this list. It is not a repaint: no tilt,');
out.push('no folded corner, a semi-transparent panel with corner brackets, a condensed');
out.push('uppercase title and a different font. It is also plain data, like all the');
out.push('others — if it had needed one line of its own CSS, the token set would have');
out.push('been wrong.');
out.push('');

fs.writeFileSync(path.join(ROOT, 'docs', 'THEMES.md'), out.join('\n'));
console.log('wrote docs/THEMES.md (' + (Object.keys(ctx.DEFAULTS).length - 3) + ' tokens)');
